language: node_js
node_js:
  - 8.9
cache:
  directories:
  - node_modules
  - med-inventory/node_modules
before_install:
  - npm install -g firebase-tools
  - cd med-inventory
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master